import type { Metadata } from 'next'
import './globals.css'
import { poppins } from './fonts'
import { FaRegHeart } from 'react-icons/fa';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <header>
          <div className="header-content-left">
            <Link href="/">
              <h1>Kave Home</h1>
            </Link>
          </div>
          <div className='header-content-right'>
            <Link href="/favoritos">
                <FaRegHeart size={20} color="black"/> 
            </Link>
          </div>
        </header>
        <main>
          {children}
        </main> 
      </body>
    </html>
  )
}
